[project]
name = "sample-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "d-coder22", email = "amitnmf@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sample-backend = "sample_backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
